export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const ADD_TO ='ADD_TO_BASKET'
export const FETCH_USERS ='FETCH_USERS'
export const FETCH_USER_ID ='FETCH_USER_ID'
export const REMOVE_FROM_FAVORITES_USER ='REMOVE_FROM_FAVORITES_USER'